<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>hgs-redisson-service-framework</artifactId>
        <groupId>com.hgs</groupId>
        <version>${revision}</version>
    </parent>

    <artifactId>hgs-repeat-execute-limit-framework</artifactId>
    <name>hgs-repeat-execute-limit-framework</name>
    <description>防重复执行幂等工具</description>

    <dependencies>
        <dependency>
            <groupId>com.hgs</groupId>
            <artifactId>hgs-redisson-common-framework</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.hgs</groupId>
            <artifactId>hgs-service-lock-framework</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>
</project>